# Generated by Django 6.0.4 on 2026-04-22 21:10

import django.db.models.deletion
import smart_selects.db_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DictType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='分类名称')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='分类编码(英文)')),
                ('remark', models.CharField(blank=True, max_length=200, null=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '字典分类',
                'verbose_name_plural': '字典分类',
            },
        ),
        migrations.CreateModel(
            name='DictItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100, verbose_name='显示名称')),
                ('value', models.CharField(max_length=100, verbose_name='存储值')),
                ('extend', models.JSONField(blank=True, default=dict, null=True, verbose_name='扩展配置')),
                ('sort', models.IntegerField(default=1, verbose_name='排序')),
                ('status', models.BooleanField(default=True, verbose_name='启用')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='roomInfo.dictitem', verbose_name='父级项')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='roomInfo.dicttype', verbose_name='所属分类')),
            ],
            options={
                'verbose_name': '字典数据',
                'verbose_name_plural': '字典数据',
            },
        ),
        migrations.CreateModel(
            name='RoomInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(max_length=100, verbose_name='机房名称')),
                ('room_name_img', models.ImageField(blank=True, null=True, upload_to='room/name/', verbose_name='机房全貌图片')),
                ('room_length', models.FloatField(blank=True, null=True, verbose_name='机房长度(m)')),
                ('room_length_img', models.ImageField(blank=True, null=True, upload_to='room/length/', verbose_name='机房长度图片')),
                ('room_width', models.FloatField(blank=True, null=True, verbose_name='机房宽度(m)')),
                ('room_width_img', models.ImageField(blank=True, null=True, upload_to='room/width/', verbose_name='机房宽度图片')),
                ('room_height', models.FloatField(blank=True, null=True, verbose_name='机房高度(m)')),
                ('room_height_img', models.ImageField(blank=True, null=True, upload_to='room/height/', verbose_name='机房高度图片')),
                ('cabinet_count', models.IntegerField(blank=True, null=True, verbose_name='网络机柜数')),
                ('cabinet_count_img', models.ImageField(blank=True, null=True, upload_to='room/cabinet/', verbose_name='网络机柜图片')),
                ('odf_count', models.IntegerField(blank=True, null=True, verbose_name='ODF/MODF数量')),
                ('odf_count_img', models.ImageField(blank=True, null=True, upload_to='room/odf/', verbose_name='ODF图片')),
                ('power_cabinet_count', models.IntegerField(blank=True, null=True, verbose_name='电源列头柜数量')),
                ('power_cabinet_count_img', models.ImageField(blank=True, null=True, upload_to='room/power_cabinet/')),
                ('switch_power_count', models.IntegerField(blank=True, null=True, verbose_name='开关电源数量')),
                ('switch_power_count_img', models.ImageField(blank=True, null=True, upload_to='room/switch_power/')),
                ('switch_power_model', models.CharField(blank=True, max_length=100, null=True, verbose_name='开关电源型号')),
                ('switch_power_model_img', models.ImageField(blank=True, null=True, upload_to='room/switch_power/')),
                ('switch_power_capacity', models.CharField(blank=True, max_length=100, null=True, verbose_name='开关电源容量')),
                ('switch_power_capacity_img', models.ImageField(blank=True, null=True, upload_to='room/switch_power/')),
                ('switch_power_factory', models.CharField(blank=True, max_length=100, null=True, verbose_name='开关电源厂家')),
                ('switch_power_factory_img', models.ImageField(blank=True, null=True, upload_to='room/switch_power/')),
                ('switch_power_date', models.DateField(blank=True, null=True, verbose_name='开关电源出厂日期')),
                ('switch_power_date_img', models.ImageField(blank=True, null=True, upload_to='room/switch_power/')),
                ('switch_module_model', models.CharField(blank=True, max_length=100, null=True)),
                ('switch_module_model_img', models.ImageField(blank=True, null=True, upload_to='room/module/')),
                ('switch_module_capacity', models.CharField(blank=True, max_length=100, null=True)),
                ('switch_module_capacity_img', models.ImageField(blank=True, null=True, upload_to='room/module/')),
                ('switch_module_count', models.IntegerField(blank=True, null=True)),
                ('switch_module_count_img', models.ImageField(blank=True, null=True, upload_to='room/module/')),
                ('battery_model', models.CharField(blank=True, max_length=100, null=True, verbose_name='电池型号')),
                ('battery_model_img', models.ImageField(blank=True, null=True, upload_to='room/battery/')),
                ('battery_capacity', models.CharField(blank=True, max_length=100, null=True, verbose_name='电池容量')),
                ('battery_capacity_img', models.ImageField(blank=True, null=True, upload_to='room/battery/')),
                ('battery_factory', models.CharField(blank=True, max_length=100, null=True, verbose_name='电池厂家')),
                ('battery_factory_img', models.ImageField(blank=True, null=True, upload_to='room/battery/')),
                ('battery_group_count', models.IntegerField(blank=True, null=True, verbose_name='电池组数')),
                ('battery_group_count_img', models.ImageField(blank=True, null=True, upload_to='room/battery/')),
                ('ac_model', models.CharField(blank=True, max_length=100, null=True, verbose_name='空调型号')),
                ('ac_model_img', models.ImageField(blank=True, null=True, upload_to='room/ac/')),
                ('ac_capacity', models.CharField(blank=True, max_length=100, null=True, verbose_name='空调容量')),
                ('ac_capacity_img', models.ImageField(blank=True, null=True, upload_to='room/ac/')),
                ('ac_factory', models.CharField(blank=True, max_length=100, null=True, verbose_name='空调厂家')),
                ('ac_factory_img', models.ImageField(blank=True, null=True, upload_to='room/ac/')),
                ('ac_count', models.IntegerField(blank=True, null=True, verbose_name='空调数量')),
                ('ac_count_img', models.ImageField(blank=True, null=True, upload_to='room/ac/')),
                ('generator_model', models.CharField(blank=True, max_length=100, null=True, verbose_name='油机型号')),
                ('generator_model_img', models.ImageField(blank=True, null=True, upload_to='room/generator/')),
                ('generator_capacity', models.CharField(blank=True, max_length=100, null=True, verbose_name='油机容量')),
                ('generator_capacity_img', models.ImageField(blank=True, null=True, upload_to='room/generator/')),
                ('generator_factory', models.CharField(blank=True, max_length=100, null=True, verbose_name='油机厂家')),
                ('generator_factory_img', models.ImageField(blank=True, null=True, upload_to='room/generator/')),
                ('generator_count', models.IntegerField(blank=True, null=True, verbose_name='油机数量')),
                ('generator_count_img', models.ImageField(blank=True, null=True, upload_to='room/generator/')),
                ('ac_box_model', models.CharField(blank=True, max_length=100, null=True, verbose_name='交流配电箱型号')),
                ('ac_box_model_img', models.ImageField(blank=True, null=True, upload_to='room/ac_box/')),
                ('ac_box_capacity', models.CharField(blank=True, max_length=100, null=True, verbose_name='配电箱容量')),
                ('ac_box_capacity_img', models.ImageField(blank=True, null=True, upload_to='room/ac_box/')),
                ('ac_box_factory', models.CharField(blank=True, max_length=100, null=True, verbose_name='配电箱厂家')),
                ('ac_box_factory_img', models.ImageField(blank=True, null=True, upload_to='room/ac_box/')),
                ('ac_box_count', models.IntegerField(blank=True, null=True, verbose_name='配电箱数量')),
                ('ac_box_count_img', models.ImageField(blank=True, null=True, upload_to='room/ac_box/')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('area', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='city', chained_model_field='parent', limit_choices_to={'type__code': 'AREA'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='room_area', to='roomInfo.dictitem', verbose_name='区县')),
                ('city', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='province', chained_model_field='parent', limit_choices_to={'type__code': 'CITY'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='room_city', to='roomInfo.dictitem', verbose_name='地市')),
                ('province', models.ForeignKey(blank=True, limit_choices_to={'type__code': 'PROVINCE'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='room_province', to='roomInfo.dictitem', verbose_name='省份')),
                ('station', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='area', chained_model_field='parent', limit_choices_to={'type__code': 'STATION'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='room_station', to='roomInfo.dictitem', verbose_name='局站名称')),
                ('station_level', models.ForeignKey(blank=True, limit_choices_to={'type__code': 'STATION_LEVEL'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='room_level', to='roomInfo.dictitem', verbose_name='局站等级')),
            ],
            options={
                'verbose_name': '机房信息',
                'verbose_name_plural': '机房信息列表',
                'ordering': ['-id'],
            },
        ),
    ]
