# Generated by Django 6.0.4 on 2026-04-24 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roomInfo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roominfo',
            name='switch_module_capacity',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='开关电源模块容量'),
        ),
        migrations.AlterField(
            model_name='roominfo',
            name='switch_module_count',
            field=models.IntegerField(blank=True, null=True, verbose_name='开关电源模块数量'),
        ),
        migrations.AlterField(
            model_name='roominfo',
            name='switch_module_model',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='开关电源模块型号'),
        ),
    ]
