# Generated by Django 6.0.4 on 2026-04-24 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roomInfo', '0002_alter_roominfo_switch_module_capacity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roominfo',
            name='ac_box_capacity_img',
            field=models.ImageField(blank=True, null=True, upload_to='room/ac_box/', verbose_name='配电箱容量图片'),
        ),
        migrations.AlterField(
            model_name='roominfo',
            name='ac_box_count_img',
            field=models.ImageField(blank=True, null=True, upload_to='room/ac_box/', verbose_name='配电箱数量图片'),
        ),
        migrations.AlterField(
            model_name='roominfo',
            name='ac_box_factory_img',
            field=models.ImageField(blank=True, null=True, upload_to='room/ac_box/', verbose_name='配电箱厂家图片'),
        ),
        migrations.AlterField(
            model_name='roominfo',
            name='ac_box_model_img',
            field=models.ImageField(blank=True, null=True, upload_to='room/ac_box/', verbose_name='交流配电室型号图片'),
        ),
        migrations.AlterField(
            model_name='roominfo',
            name='ac_capacity_img',
            field=models.ImageField(blank=True, null=True, upload_to='room/ac/', verbose_name='空调容量图片'),
        ),
        migrations.AlterField(
            model_name='roominfo',
            name='ac_count_img',
            field=models.ImageField(blank=True, null=True, upload_to='room/ac/', verbose_name='空调数量图片'),
        ),
        migrations.AlterField(
            model_name='roominfo',
            name='ac_factory_img',
            field=models.ImageField(blank=True, null=True, upload_to='room/ac/', verbose_name='空调厂家图片'),
        ),
        migrations.AlterField(
            model_name='roominfo',
            name='ac_model_img',
            field=models.ImageField(blank=True, null=True, upload_to='room/ac/', verbose_name='空调型号图片'),
        ),
        migrations.AlterField(
            model_name='roominfo',
            name='battery_capacity_img',
            field=models.ImageField(blank=True, null=True, upload_to='room/battery/', verbose_name='电池容量图片'),
        ),
        migrations.AlterField(
            model_name='roominfo',
            name='battery_factory_img',
            field=models.ImageField(blank=True, null=True, upload_to='room/battery/', verbose_name='电池厂家图片'),
        ),
        migrations.AlterField(
            model_name='roominfo',
            name='battery_group_count_img',
            field=models.ImageField(blank=True, null=True, upload_to='room/battery/', verbose_name='电池组数图片'),
        ),
        migrations.AlterField(
            model_name='roominfo',
            name='battery_model_img',
            field=models.ImageField(blank=True, null=True, upload_to='room/battery/', verbose_name='电池型号图片'),
        ),
        migrations.AlterField(
            model_name='roominfo',
            name='cabinet_count_img',
            field=models.ImageField(blank=True, null=True, upload_to='room/cabinet/', verbose_name='网络机柜数量图片'),
        ),
        migrations.AlterField(
            model_name='roominfo',
            name='generator_capacity_img',
            field=models.ImageField(blank=True, null=True, upload_to='room/generator/', verbose_name='油机容量图片'),
        ),
        migrations.AlterField(
            model_name='roominfo',
            name='generator_count_img',
            field=models.ImageField(blank=True, null=True, upload_to='room/generator/', verbose_name='油机数量图片'),
        ),
        migrations.AlterField(
            model_name='roominfo',
            name='generator_factory_img',
            field=models.ImageField(blank=True, null=True, upload_to='room/generator/', verbose_name='油机厂家图片'),
        ),
        migrations.AlterField(
            model_name='roominfo',
            name='generator_model_img',
            field=models.ImageField(blank=True, null=True, upload_to='room/generator/', verbose_name='油机型号图片'),
        ),
        migrations.AlterField(
            model_name='roominfo',
            name='odf_count_img',
            field=models.ImageField(blank=True, null=True, upload_to='room/odf/', verbose_name='ODF/MODF数量图片'),
        ),
        migrations.AlterField(
            model_name='roominfo',
            name='power_cabinet_count_img',
            field=models.ImageField(blank=True, null=True, upload_to='room/power_cabinet/', verbose_name='电源列头柜数量图片'),
        ),
        migrations.AlterField(
            model_name='roominfo',
            name='switch_module_capacity_img',
            field=models.ImageField(blank=True, null=True, upload_to='room/module/', verbose_name='开关电源模块容量图片'),
        ),
        migrations.AlterField(
            model_name='roominfo',
            name='switch_module_count_img',
            field=models.ImageField(blank=True, null=True, upload_to='room/module/', verbose_name='开关电源模块数量图片'),
        ),
        migrations.AlterField(
            model_name='roominfo',
            name='switch_module_model_img',
            field=models.ImageField(blank=True, null=True, upload_to='room/module/', verbose_name='开关电源模块型号图片'),
        ),
        migrations.AlterField(
            model_name='roominfo',
            name='switch_power_capacity_img',
            field=models.ImageField(blank=True, null=True, upload_to='room/switch_power/', verbose_name='开关电源容量图片'),
        ),
        migrations.AlterField(
            model_name='roominfo',
            name='switch_power_count_img',
            field=models.ImageField(blank=True, null=True, upload_to='room/switch_power/', verbose_name='开关电源数量图片'),
        ),
        migrations.AlterField(
            model_name='roominfo',
            name='switch_power_date_img',
            field=models.ImageField(blank=True, null=True, upload_to='room/switch_power/', verbose_name='开关电源出厂日期图片'),
        ),
        migrations.AlterField(
            model_name='roominfo',
            name='switch_power_factory_img',
            field=models.ImageField(blank=True, null=True, upload_to='room/switch_power/', verbose_name='开关电源厂家图片'),
        ),
        migrations.AlterField(
            model_name='roominfo',
            name='switch_power_model_img',
            field=models.ImageField(blank=True, null=True, upload_to='room/switch_power/', verbose_name='开关电源型号图片'),
        ),
    ]
