# Generated by Django 5.2.10 on 2026-06-07 17:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_track_inspection'),
        ('roomInfo', '0003_alter_roominfo_ac_box_capacity_img_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dictitem',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='dicttype',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='roominfo',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='InspectionSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(verbose_name='开始时间')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('status', models.CharField(choices=[('active', '巡检中'), ('completed', '已完成')], default='active', max_length=20, verbose_name='状态')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('admin_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspection_sessions', to='login.roomadminuser', verbose_name='巡检管理员')),
                ('station', models.ForeignKey(limit_choices_to={'type__code': 'STATION'}, on_delete=django.db.models.deletion.PROTECT, related_name='inspection_sessions', to='roomInfo.dictitem', verbose_name='巡检局站')),
            ],
            options={
                'verbose_name': '巡检会话',
                'verbose_name_plural': '巡检会话列表',
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='InspectionTrackPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField(verbose_name='纬度')),
                ('longitude', models.FloatField(verbose_name='经度')),
                ('accuracy', models.FloatField(blank=True, null=True, verbose_name='定位精度(m)')),
                ('altitude', models.FloatField(blank=True, null=True, verbose_name='海拔(m)')),
                ('timestamp', models.DateTimeField(verbose_name='定位时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='记录时间')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='track_points', to='roomInfo.inspectionsession', verbose_name='所属巡检会话')),
            ],
            options={
                'verbose_name': '巡检轨迹点',
                'verbose_name_plural': '巡检轨迹点列表',
                'ordering': ['timestamp'],
            },
        ),
    ]
