"""
Django settings for room project.

Generated by 'django-admin startproject' using Django 6.0.4.
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
DATA_DIR = BASE_DIR / "data"

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get("SECRET_KEY", 'django-insecure-z!-t31+1i1mv+19i@tnkgi&#hd3f7=^6&7lepc%-6dbe@iz26d')
# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DEBUG", "true").lower()
print(f'Debug modus is turned {"on" if DEBUG else "off"}')

MAIN_HOST = os.environ.get("MAIN_HOST", "http://localhost")
HOSTS = os.environ.get("HOSTS", "http://localhost,http://127.0.0.1").split(",")
CSRF_TRUSTED_ORIGINS = HOSTS
ALLOWED_HOSTS = ['*']
CORS_ALLOWED_ORIGINS = HOSTS
CORS_ALLOW_ALL_ORIGINS = True if DEBUG or os.environ.get("ALLOW_ALL_HOSTS", "false").lower() == "true" else False
CORS_ALLOW_CREDENTIALS = True

# Application definition
INSTALLED_APPS = [
    'import_export',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    # 🔥 固定静态文件必备
    'django.contrib.staticfiles',
    'corsheaders',
    'rest_framework',
    'login',
    'roomInfo',
    'smart_selects',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'room.urls'

MIGRATION_MODULES = {
    "login": "data.db_migrations.login",
    "roomInfo": "data.db_migrations.roomInfo"
}

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'room.wsgi.application'

# Database
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        "NAME": DATA_DIR / 'db.sqlite3',
        "OPTIONS": {
            "timeout": 20,
        },
    }
    if os.environ.get("POSTGRES_HOST", None) is None
    else {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.environ.get("POSTGRES_DB", "postgres"),
        "USER": os.environ.get("POSTGRES_USER", "postgres"),
        "PASSWORD": os.environ.get("POSTGRES_PASSWORD", ""),
        "HOST": os.environ.get("POSTGRES_HOST", "localhost"),
        "PORT": "",
    }
}

# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

# Internationalization
LANGUAGE_CODE = 'zh-hans'
TIME_ZONE = os.environ.get("TIME_ZONE", "Asia/Shanghai")
USE_I18N = True
USE_TZ = False

# 媒体文件配置
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR,'media')

# 缓存
CACHES = {
    'default': ({
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
    } if DEBUG else {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": "redis://0.0.0.0:6379/1",
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
            "CONNECTION_POOL_KWARGS": {"max_connections": 100,"retry_on_timeout": True},
            "SOCKET_CONNECT_TIMEOUT": 5,
            "SOCKET_TIMEOUT": 5,
        }
    })
}

# 🔥 【终极修复】静态文件配置（生产环境100%可用）
STATIC_URL = '/static/'
STATIC_ROOT = '/app/static_collect'
# 固定静态文件存储（WhiteNoise）
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# SimpleUI 配置
SIMPLEUI_LOGIN_PC = False
SIMPLEUI_HOME_INFO = False
SIMPLEUI_HOME_ANALYSIS = False
SIMPLEUI_DEFAULT_TITLE = "动环安全评估管理系统"
SIMPLEUI_DEFAULT_HEADER = "动环安全评估管理系统"
SIMPLEUI_THEME = 'blue'

# 文件上传大小
DATA_UPLOAD_MAX_MEMORY_SIZE = 52428800
FILE_UPLOAD_MAX_MEMORY_SIZE = 52428800