# Generated by Django 6.0.4 on 2026-04-22 21:08

import django.db.models.deletion
import smart_selects.db_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('roomInfo', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomAdminUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=11, unique=True, verbose_name='手机号(账号)')),
                ('name', models.CharField(blank=True, max_length=20, null=True, verbose_name='姓名')),
                ('password', models.CharField(blank=True, max_length=128, verbose_name='密码')),
                ('login_status', models.SmallIntegerField(choices=[(0, '未登录'), (1, '已登录')], default=0, help_text='0-未登录 1-已登录', verbose_name='登录状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('area', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='city', chained_model_field='parent', limit_choices_to={'type__code': 'AREA'}, on_delete=django.db.models.deletion.PROTECT, related_name='admin_area', to='roomInfo.dictitem', verbose_name='区县')),
                ('city', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='province', chained_model_field='parent', limit_choices_to={'type__code': 'CITY'}, on_delete=django.db.models.deletion.PROTECT, related_name='admin_city', to='roomInfo.dictitem', verbose_name='地市')),
                ('province', models.ForeignKey(limit_choices_to={'type__code': 'PROVINCE'}, on_delete=django.db.models.deletion.PROTECT, related_name='admin_province', to='roomInfo.dictitem', verbose_name='省份')),
                ('station', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='area', chained_model_field='parent', limit_choices_to={'type__code': 'STATION'}, on_delete=django.db.models.deletion.PROTECT, related_name='admin_station', to='roomInfo.dictitem', unique=True, verbose_name='负责局站')),
                ('station_level', models.ForeignKey(limit_choices_to={'type__code': 'STATION_LEVEL'}, on_delete=django.db.models.deletion.PROTECT, related_name='admin_level', to='roomInfo.dictitem', verbose_name='局站等级')),
            ],
            options={
                'verbose_name': '机房管理员',
                'verbose_name_plural': '机房管理员列表',
                'ordering': ['-created_at'],
            },
        ),
    ]
